---
# Note: acl is needed because ansible needs facl to execute commands as an
# upriviledged user.
- name: Install weechat related packages
  package: name={{ item }} state=present
  loop:
    - weechat
    - acl

- name: Initialize profiles
  command: weechat -r "{{ item.init | join('" -r "') }}" -r "/EXIT"
  become: yes
  become_user: "{{ item.user }}"
  args:
    creates: "/home/{{ item.user }}/.weechat"
  loop: "{{ weechat | default([]) }}"

- name: Ensure the proper systemd directories exist
  file:
    path: "/home/{{ item.user }}/.config/systemd/user/default.target.wants"
    state: directory
    owner: "{{ item.user }}"
    group: "{{ item.user }}"
    recurse: yes
  when: item.tmuxautostart
  loop: "{{ weechat | default([]) }}"

- name: Install tmux autostart script
  copy:
    src: files/config/systemd/user/weechat.service
    dest: "/home/{{ item.user }}/.config/systemd/user/weechat.service"
    owner: "{{ item.user }}"
    group: "{{ item.user }}"
  when: item.tmuxautostart
  loop: "{{ weechat | default([]) }}"

- name: Enable linger for users of the tmux autostart service
  command: loginctl enable-linger {{ item.user }}
  become: yes
  become_user: root
  args:
    creates: "/var/lib/systemd/linger/{{ item.user }}"
  when: item.tmuxautostart
  loop: "{{ weechat | default([]) }}"

- name: Enable the tmux autostart service
  file:
    path: "/home/{{ item.user }}/.config/systemd/user/default.target.wants/weechat.service"
    src: "/home/{{ item.user }}/.config/systemd/user/weechat.service"
    owner: "{{ item.user }}"
    group: "{{ item.user }}"
    state: link
    follow: false
  when: item.tmuxautostart
  loop: "{{ weechat | default([]) }}"

