---
# Note: acl is needed because ansible needs facl to execute commands as an
# upriviledged user.
- name: Install weechat related packages
  package: name={{ item }} state=present
  loop:
    - weechat
    - acl

- name: Initialize profiles
  command: weechat -r "{{ item.value.init | join('" -r "') }}" -r "/EXIT"
  become: yes
  become_user: "{{ item.key }}"
  args:
    creates: "/home/{{ item.key }}/.weechat"
  loop: "{{ weechat | default({}) | dict2items }}"
