---
# Note: acl is needed because ansible needs facl to execute commands as an
# upriviledged user.
- name: Install weechat related packages
  package: name={{ item }} state=present
  loop:
    - weechat
    - acl

- name: Configure weechat for user {{ weechat_user }}
  command: weechat -r "{{ weechat_commands | join('" -r "') }}" -r "/EXIT"
  become: yes
  become_user: "{{ weechat_user }}"
  args:
    creates: "/home/{{ weechat_user }}/.weechat"
  when: weechat_user is defined and weechat_commands | default([]) | length > 0
