---
#ansible_user: pi
#ansible_ssh_pass: raspberry

users:
  - username: "{{ ssh_user }}"
    authorized_keys:
      - "{{ ssh_pubkey_t450 }}"
      - "{{ ssh_pubkey_work }}"
      - "{{ ssh_pubkey_gpg }}"
    home_create: yes
    shell: /bin/bash
  - username: "android"
    authorized_keys:
      - "{{ ssh_pubkey_t450 }}"
      - "{{ ssh_pubkey_work }}"
      - "{{ ssh_pubkey_gpg }}"
      - "command=\"/usr/local/bin/rrsync /mnt/android/\",no-agent-forwarding,no-port-forwarding,no-pty,no-user-rc,no-X11-forwarding {{ ssh_pubkey_op3t_syncopoly }}"
    home_create: yes
    shell: /bin/bash
  - username: "mail"
    authorized_keys:
      - "{{ ssh_pubkey_t450 }}"
      - "{{ ssh_pubkey_work }}"
      - "{{ ssh_pubkey_gpg }}"
    home_create: yes
    shell: /bin/bash


network_interfaces_manage_devices: true
network_interfaces_interfaces:
  - device: eth0
    family: inet
    method: dhcp
    triggers:
      - allow-hotplug
  - device: usb0
    family: inet
    method: dhcp
    triggers:
      - allow-hotplug

wireguard:
  wg0:
    privkey: "{{ vault_wg0_privkey }}"
    peers:
      dedibox: "{{ wireguard_global_settings.wg0.peers.dedibox }}"
    auto_assign_ranges: "{{ wireguard_global_settings.wg0.auto_assign_ranges }}"
    mtu: "{{ wireguard_global_settings.wg0.mtu }}"
    dns: "{{ wireguard_global_settings.wg0.dns }}"

extrastorage:
  - path: "/mnt"
    src: "UUID={{ vault_sandisk_256G_uuid }}"

mpop_user: "mail"
mpop_mpoprc:
  - |
    # defaults
    defaults
    tls on
    # gmail
    account gmail
    host pop.gmail.com
    user {{ vault_msmtp_user }}
    password {{ vault_msmtp_password }}
    keep on
    only_new off
    tls_starttls off
    delivery mbox /mnt/{{ mpop_user }}/{{ vault_msmtp_user }}@gmail.com.mbox
    # Set a default account
    account default : gmail

nftables_includes:
  http:
    - |
      add rule inet filter input tcp dport 80 counter accept comment "accept HTTP"

host_roles:
  - common
  - chmduquesne.network_interfaces
  - chmduquesne.wireguard
  - extrastorage
  - mpop
  - rrsync
  - chmduquesne.nftables
