---
#ansible_user: pi
#ansible_ssh_pass: raspberry

users:
  - username: "{{ ssh_user }}"
    authorized_keys:
      - "{{ ssh_pubkey_t450 }}"
      - "{{ ssh_pubkey_work }}"
    home_create: yes
    shell: /bin/bash
  - username: "android"
    authorized_keys:
      - "{{ ssh_pubkey_t450 }}"
      - "{{ ssh_pubkey_work }}"
      - "{{ ssh_pubkey_op3t_syncopoly }}"
    home_create: yes
    shell: /bin/bash


network_interfaces_manage_devices: true
network_interfaces_interfaces:
  - device: eth0
    family: inet
    method: dhcp
    triggers:
      - allow-hotplug
  - device: usb0
    family: inet
    method: dhcp
    triggers:
      - allow-hotplug

wireguard_override:
  wg0:
    privkey: "{{ vault_wg0_privkey }}"
    pubkey: "{{ wireguard_default.wg0.peers.backupbox.pubkey }}"

wireguard: "{{ wireguard_client|combine(wireguard_override, recursive=True) }}"

host_roles:
  - common
  - chmduquesne.network_interfaces
  - chmduquesne.wireguard
