---
# No longer Necessary after users/sudo are setup
ansible_become_user: root
ansible_become_method: su
ansible_become_pass: "{{ vault_ansible_become_pass }}"

ssh_user: "{{ vault_desktop_user }}"
ansible_user: "{{ ssh_user }}"
users:
  - username: "{{ ssh_user }}"
    authorized_keys:
      - "{{ ssh_pubkey_t450 }}"
      - "{{ ssh_pubkey_work }}"
    home_create: yes
    shell: /bin/bash
promoted:
  - name: "{{ ssh_user }}"
    promote: ALL
    nopasswd: true

host_roles:
  - common
  - desktop
