---
#ansible_user: pi

wireguard:
  wg0:
    privkey: "{{ vault_wg0_privkey }}"
    mtu: "{{ wireguard_wg0_mtu }}"
    auto_assign_ips: "{{ wireguard_wg0_auto_assign_ips }}"
    peers: "{{ wireguard_wg0_peers }}"
    gw: "{{ wireguard_wg0_gw }}"

iptables_custom_rules:
  - name: "wg0_dns"
    rules: |
      -A INPUT -i {{ wireguard.wg0.gw.in.interface }} -p tcp -m tcp --dport 53 -m conntrack --ctstate NEW -j ACCEPT
      -A INPUT -i {{ wireguard.wg0.gw.in.interface }} -p udp -m udp --dport 53 -m conntrack --ctstate NEW -j ACCEPT

ip6tables_custom_rules: "{{ iptables_custom_rules }}"

network_interfaces_manage_devices: true
network_interfaces_interfaces:
  - device: eth0
    family: inet
    method: dhcp
    triggers:
      - allow-hotplug
  - device: usb0
    family: inet
    method: dhcp
    triggers:
      - allow-hotplug
  - device: wlan0
    family: inet6
    method: static
    address: "{{ wireguard.wg0.gw.routed_inet6.prefix }}::1"
    netmask: "{{ wireguard.wg0.gw.routed_inet6.mask }}"
    hostapd: /etc/hostapd/hostapd.conf
  - device: wlan0
    family: inet
    method: static
    address: 192.168.1.1
    netmask: 24

hostapd:
  ssid: "{{ vault_hostapd_ssid }}"
  wpa_passphrase: "{{ vault_hostapd_wpa_passphrase }}"

dnsmasq_dnsmasq_conf:
  - |
    domain-needed
    bogus-priv
    no-resolv
    server={{ vault_wg0_upstream_dns }}
    dnssec
    conf-file=/usr/share/dnsmasq-base/trust-anchors.conf
    local=/rpi/
    domain=rpi
    dhcp-fqdn
    dhcp-range=192.168.1.2,192.168.1.254,12h
    dhcp-authoritative
    dhcp-range=::,constructor:wlan0,ra-stateless,ra-names,12h
    dhcp-option={{ wireguard.wg0.gw.in.interface }},26,{{ wireguard.wg0.mtu }}
    ra-param=mtu:{{ wireguard.wg0.mtu }}
    enable-ra
