---
#ansible_user: pi

wireguard:
  wg0:
    privkey: "{{ vault_wg0_privkey }}"
    pubkey: "{{ vault_wg0_pubkey }}"
    allowed_ips: "{{ vault_wg0_in_gw_inet6_prefix }}::/{{ vault_wg0_in_gw_inet6_mask }}"
    listenport: 4000
    in_gw:
      interface: wlan0
      inet6_prefix: "{{ vault_wg0_in_gw_inet6_prefix }}"
      inet6_mask: "{{ vault_wg0_in_gw_inet6_mask }}"
      inet_prefix: "{{ vault_wg0_in_gw_inet_prefix }}"
      inet_mask: "{{ vault_wg0_in_gw_inet_mask }}"

network_interfaces_manage_devices: true
network_interfaces_interfaces:
  - device: eth0
    family: inet
    method: dhcp
    triggers:
      - allow-hotplug
  - device: usb0
    family: inet
    method: dhcp
    triggers:
      - allow-hotplug
  - device: wlan0
    family: inet6
    method: static
    address: "{{ wireguard.wg0.in_gw.inet6_prefix }}::1"
    netmask: "{{ wireguard.wg0.in_gw.inet6_mask }}"
    hostapd: /etc/hostapd/hostapd.conf
  - device: wlan0
    family: inet
    method: static
    address: 192.168.1.1
    netmask: 24

hostapd:
  ssid: "{{ vault_hostapd_ssid }}"
  wpa_passphrase: "{{ vault_hostapd_wpa_passphrase }}"

dnsmasq_dnsmasq_conf:
  - |
    domain-needed
    bogus-priv
    no-resolv
    server={{ vault_wg0_upstream_dns }}
    dnssec
    conf-file=/usr/share/dnsmasq-base/trust-anchors.conf
    local=/rpi/
    domain=rpi
    dhcp-fqdn
    dhcp-range=192.168.1.2,192.168.1.254,12h
    dhcp-authoritative
    dhcp-range=::,constructor:wlan0,ra-stateless,ra-names,12h
    dhcp-option={{ wireguard.wg0.in_gw.interface }},26,1360
    ra-param=mtu:1360
    enable-ra
