---
#ansible_user: pi

wireguard:
  wg0:
    privkey: "{{ vault_wg0_privkey }}"
    pubkey: "{{ vault_wg0_pubkey }}"
    allowed_ips: "{{ vault_wg0_in_gw_inet6_prefix }}::/{{ vault_wg0_in_gw_inet6_mask }}"
    listenport: 4000
    in_gw:
      interface: wlan0
      inet6_prefix: "{{ vault_wg0_in_gw_inet6_prefix }}"
      inet6_mask: "{{ vault_wg0_in_gw_inet6_mask }}"
      inet_prefix: "{{ vault_wg0_in_gw_inet_prefix }}"
      inet_mask: "{{ vault_wg0_in_gw_inet_mask }}"

network_interfaces_manage_devices: true
network_interfaces_interfaces:
  - device: eth0
    family: inet
    method: dhcp
    triggers:
      - allow-hotplug
  - device: usb0
    family: inet
    method: dhcp
    triggers:
      - allow-hotplug
  - device: wlan0
    family: inet6
    method: static
    address: "{{ wireguard.wg0.in_gw.inet6_prefix }}::1"
    netmask: "{{ wireguard.wg0.in_gw.inet6_mask }}"
    hostapd: /etc/hostapd/hostapd.conf
  - device: wlan0
    family: inet
    method: static
    address: 192.168.1.1
    netmask: 24

hostapd:
  ssid: "{{ vault_hostapd_ssid }}"
  wpa_passphrase: "{{ vault_hostapd_wpa_passphrase }}"

radvd:
  interface: "{{ wireguard.wg0.in_gw.interface }}"
  inet6_prefix: "{{ wireguard.wg0.in_gw.inet6_prefix }}"
  inet6_mask: "{{ wireguard.wg0.in_gw.inet6_mask }}"
  rdnss: "{{ wireguard.wg0.in_gw.inet6_prefix }}::1"

unbound:
  recursive: false
  controllers:
    - 'fd1a:6126:2887::/48'
    - '10.0.0.0/8'
    - '192.168.1.0/24'
    - '{{ vault_wg0_in_gw_inet6_prefix }}::/{{ vault_wg0_in_gw_inet6_mask }}'

dhcpd_mode: 'server'
dhcpd_ipversion: '4'
dhcpd_interfaces:
  - 'wlan0'
dhcpd_authoritative: true
dhcpd_nameservers:
  - '192.168.1.1'
dhcpd_subnets:
  - subnet: '192.168.1.0/24'
    routers: '192.168.1.1'
    comment: "basic subnet"
    pools:
      - range: '192.168.1.2 192.168.1.254'
    options: |
      option interface-mtu 1412;
