---
#ansible_user: pi

wireguard:
  wg0:
    privkey: "{{ vault_wg0_privkey }}"
    pubkey: "{{ vault_wg0_pubkey }}"
    allowed_ips: "{{ vault_wg0_in_gw_inet6_prefix }}::/{{ vault_wg0_in_gw_inet6_mask }}"
    listenport: 4000
    in_gw:
      interface: wlan0
      inet6_prefix: "{{ vault_wg0_in_gw_inet6_prefix }}"
      inet6_mask: "{{ vault_wg0_in_gw_inet6_mask }}"

network_interfaces_manage_devices: true
network_interfaces_interfaces:
  - device: eth0
    family: inet
    method: dhcp
    triggers:
      - allow-hotplug
  - device: usb0
    family: inet
    method: dhcp
    triggers:
      - allow-hotplug
  - device: wlan0
    family: inet6
    method: static
    address: "{{ wireguard.wg0.in_gw.inet6_prefix }}::1"
    netmask: "{{ wireguard.wg0.in_gw.inet6_mask }}"
    hostapd: /etc/hostapd/hostapd.conf

hostapd:
  ssid: "{{ vault_hostapd_ssid }}"
  wpa_passphrase: "{{ vault_hostapd_wpa_passphrase }}"

radvd:
  interface: "{{ wireguard.wg0.in_gw.interface }}"
  inet6_prefix: "{{ wireguard.wg0.in_gw.inet6_prefix }}"
  inet6_mask: "{{ wireguard.wg0.in_gw.inet6_mask }}"
  rdnss: "{{ wireguard.wg0.in_gw.inet6_prefix }}::1"

unbound:
  recursive: false
