---
#ansible_user: pi

wireguard:
  privkey: "{{ vault_wg_privkey }}"
  pubkey: "{{ vault_wg_pubkey }}"
  private_ip6: "{{ vault_wg_private_ip6 }}"
  routed_ip6: "{{ vault_wg_routed_ip6 }}"
  allowed_ips: "{{ vault_wg_private_ip6 }}, {{ vault_wg_routed_ip6 }}"
  listenport: 4000

network_interfaces_manage_devices: true
network_interfaces_interfaces:
  - device: eth0
    family: inet
    method: dhcp
    triggers:
      - allow-hotplug
  - device: usb0
    family: inet
    method: dhcp
    triggers:
      - allow-hotplug
