---
#ansible_user: pi
#ansible_ssh_pass: raspberry

_wireguard_custom:
  wg0:
    privkey: "{{ vault_wg0_privkey }}"
    pubkey: "{{ wireguard_default.wg0.peers.raspberrypi.pubkey }}"
    in_gw: wlan0
    dns: False
    # Generate an uint32 from the interface name
    table: "{{ 'wg0'|checksum|truncate(4, end='')|int(base=16) }}"

wireguard: "{{ wireguard_client|combine(_wireguard_custom, recursive=True) }}"

iptables_custom_rules:
  - name: "wg0_dns"
    rules: |
      -A INPUT -i {{ wireguard.wg0.in_gw }} -p tcp -m tcp --dport 53 -m conntrack --ctstate NEW -j ACCEPT
      -A INPUT -i {{ wireguard.wg0.in_gw }} -p udp -m udp --dport 53 -m conntrack --ctstate NEW -j ACCEPT

ip6tables_custom_rules: "{{ iptables_custom_rules }}"

# untested
nftables_includes:
  "wg0_dns":
    - |
      table inet wg0_dns {
        chain input {
            type filter hook input priority -1; policy continue;
            iif {{ wireguard.wg0.in_gw }} udp dport 53 accept comment "accept udp dns requests on {{ wireguard.wg0.in_gw }}"
            iif {{ wireguard.wg0.in_gw }} tcp dport 53 accept comment "accept tcp dns requests on {{ wireguard.wg0.in_gw }}"
        }
      }

wlan0_inet6: "{{ wireguard_default.wg0.peers.raspberrypi.allowedips.0 }}"

network_interfaces_manage_devices: true
network_interfaces_interfaces:
  - device: eth0
    family: inet
    method: dhcp
    triggers:
      - allow-hotplug
  - device: usb0
    family: inet
    method: dhcp
    triggers:
      - allow-hotplug
  - device: wlan0
    family: inet6
    method: static
    address: "{{ wlan0_inet6.split('::/')|first }}::1"
    netmask: "{{ wlan0_inet6.split('::/')|last }}"
    hostapd: /etc/hostapd/hostapd.conf
    post-up:
      - ip -6 rule add iif wlan0 lookup {{ wireguard.wg0.table }}
  - device: wlan0
    family: inet
    method: static
    address: 192.168.1.1
    netmask: 24
    post-up:
      - ip -4 rule add iif wlan0 lookup {{ wireguard.wg0.table }}

hostapd_conf:
  - |
    interface=wlan0
    hw_mode=g
    channel=10
    ieee80211d=1
    country_code=DE
    ieee80211n=1
    wmm_enabled=1
    ssid={{ vault_hostapd_ssid }}
    auth_algs=1
    wpa=2
    wpa_key_mgmt=WPA-PSK
    rsn_pairwise=CCMP
    wpa_passphrase={{ vault_hostapd_wpa_passphrase }}

dnsmasq_dnsmasq_conf:
  - |
    domain-needed
    bogus-priv
    no-resolv
    server={{ wireguard_default.wg0.dns }}
    dnssec
    conf-file=/usr/share/dnsmasq-base/trust-anchors.conf
    local=/rpi/
    domain=rpi
    dhcp-fqdn
    dhcp-range=192.168.1.2,192.168.1.254,12h
    dhcp-authoritative
    dhcp-range=::,constructor:wlan0,ra-stateless,ra-names,12h
    dhcp-option={{ wireguard.wg0.in_gw }},26,{{ wireguard.wg0.mtu }}
    ra-param=mtu:{{ wireguard.wg0.mtu }}
    enable-ra

dnsmasq_etc_default_options:
  - DNSMASQ_EXCEPT=lo

host_roles:
  - common
  - chmduquesne.network_interfaces
  - chmduquesne.wireguard
  - chmduquesne.hostapd
  - oefenweb.dnsmasq
