---
- hosts: clients
  tasks:
    - name: apply common settings
      include_role: name=common

    - name: configure wireguard
      include_role: name=chmduquesne.ansible_wireguard

    - name: configure tvheadend
      include_role: name=tvheadend

    - name: install a socks-proxy
      include_role: name=socks-proxy
