---
- hosts: clients
  tasks:
    - name: apply common settings
      include_role: name=common

    - name: configure wireguard
      include_role: name=wireguard

    - name: enable wg-quick
      systemd:
        name: "wg-quick@{{ item }}"
        enabled: yes
        state: started
      with_items: "{{ wireguard.keys() | list }}"
