---
- src: weareinteractive.users
  version: 1.10.0

- src: salamachinas.sudoers
  version: 1.1.0

- src: reallyenglish.dhclient
  version: 1.0.0

- src: chmduquesne.network_interfaces
  version: v2.0.7

- src: reallyenglish.sshd
  version: 1.1.0

- src: oefenweb.dnsmasq
  version: v2.2.10

- src: chmduquesne.wireguard
  version: 0.0.9

- src: chmduquesne.ansible_hostapd
  version: 0.0.1

- src: elboletaire.transmission
  version: 2.0.1
