---
- src: weareinteractive.users
  version: 1.10.0

- src: salamachinas.sudoers
  version: 1.1.0

- src: reallyenglish.dhclient
  version: 1.0.0

- src: chmduquesne.ansible-network-interfaces
  version: v2.0.5

- src: chmduquesne.iptables-persistent
  version: v1.0.6

- src: reallyenglish.sshd
  version: 1.1.0

- src: debops.debops
  version: v0.8.0
