---
- hosts: routers
  tasks:
    - name: apply common settings
      include_role: name=common

    - name: configure wireguard
      include_role: name=chmduquesne.wireguard

    - name: configure network
      include_role: name=chmduquesne.network_interfaces

    - name: configure hostapd
      include_role: name=chmduquesne.ansible_hostapd

    - name: configure dnsmasq
      include_role: name=oefenweb.dnsmasq
