---
- hosts: routers
  tasks:
    - name: apply common settings
      include_role: name=common

    - name: configure wireguard
      include_role: name=wireguard

    - name: inject wireguard out_gw address in unbound configuration
      set_fact:
        unbound: "{{ unbound | combine({'upstream': wireguard_upstream_dns}) }}"

    - name: apply wireguard suggested iptables rules
      iptables_raw:
        name: "{{ item.name }}"
        rules: "{{ item.rules }}"
        table: "{{ item.table | default(omit) }}"
        ipversion: "{{ item.ipversion }}"
      with_items: "{{ wireguard_suggested_iptables | default([]) }}"

    - name: configure network
      include_role: name=chmduquesne.ansible-network-interfaces

    - name: configure hostapd
      include_role: name=hostapd

    - name: configure radvd
      include_role: name=radvd

    - name: configure unbound
      include_role: name=unbound

    - name: configure dhcpd
      include_role: name=debops.dhcpd
