---
- hosts: routers
  roles:
    - franklinkim.users
    - salamachinas.sudoers
    - reallyenglish.sshd
    - chmduquesne.iptables-persistent
    - wireguard
    - chmduquesne.ansible-network-interfaces
    - hostapd
    - radvd
    - unbound
    - iptables
  tasks:
    - name: get latest vim
      package: name=vim state=latest
