---
- hosts: routers
  tasks:
    - name: apply common settings
      include_role: name=common

    - name: configure wireguard
      include_role: name=wireguard

    - name: adding suggested wireguard interfaces
      set_fact:
         network_interfaces_interfaces: "{{ network_interfaces_interfaces | default([]) }} + wireguard_suggested_interfaces"

    - name: configure network
      include_role: name=chmduquesne.ansible-network-interfaces

    - name: configure hostapd
      include_role: name=hostapd

    - name: configure dnsmasq
      include_role: name=oefenweb.dnsmasq
