---
- hosts: routers
  roles:
    - franklinkim.users
    - salamachinas.sudoers
    - reallyenglish.sshd
    - iptables-persistent
    - wireguard
    - chmduquesne.ansible-network-interfaces
    - hostapd
    - radvd
  tasks:
    - name: get latest vim
      package: name=vim state=latest
