---
- hosts: web
  roles:
    - franklinkim.users
    - salamachinas.sudoers
    - reallyenglish.dhclient
    - tersmitten.network-interfaces
    - reallyenglish.sshd
  tasks:
    - name: get latest vim
      package: name=vim state=latest
