---
- hosts: web
  roles:
    - franklinkim.users
    - salamachinas.sudoers
    - reallyenglish.sshd
    - reallyenglish.dhclient
    - chmduquesne.iptables-persistent
    - wireguard
    - chmduquesne.ansible-network-interfaces
    - unbound
  tasks:
    - name: get latest vim
      package: name=vim state=latest
