---
- hosts: web
  tasks:
    - name: apply common settings
      include_role: name=common

    - name: configure dhclient
      include_role: name=reallyenglish.dhclient

    - name: configure wireguard
      include_role: name=wireguard

    - name: adding suggested wireguard interfaces
      set_fact:
         network_interfaces_interfaces: "{{ network_interfaces_interfaces | default([]) }} + wireguard_suggested_interfaces"

    - name: configure network
      include_role: name=chmduquesne.ansible-network-interfaces

    - name: configure unbound
      include_role: name=unbound
