---
- name: Get unbound and related packages
  package: name={{ item }} state=present
  loop:
    - unbound
    - openresolv

- name: Configure /etc/unbound/unbound.conf
  template:
    src: templates/etc/unbound/unbound.conf.j2
    dest: /etc/unbound/unbound.conf
  notify:
    - restart unbound

- name: Enable service
  service: name=unbound enabled=yes use=service
  notify:
    - restart unbound
