---
- name: install iptables-persistent
  package: name=iptables-persistent state=latest
  when: ansible_os_family == "Debian"

- name: Set custom iptables rules
  iptables_raw:
    name: 'iptables_custom_rules_{{ item.name }}'
    weight: '{{ item.weight|default(omit) }}'
    keep_unmanaged: '{{ iptables_keep_unmanaged }}'
    rules: '{{ item.rules }}'
    state: '{{ item.state|default(omit) }}'
    table: '{{ item.table|default(omit) }}'
    ipversion: 4
  with_items: '{{ iptables_custom_rules }}'
  tags: iptables

- name: Set default iptables head rules
  iptables_raw:
    name: iptables_default_head
    weight: 10
    keep_unmanaged: '{{ iptables_keep_unmanaged }}'
    state: present
    rules: '{{ iptables_default_head }}'
    ipversion: 4
  tags: iptables

- name: Set default iptables tail rules
  iptables_raw:
    name: iptables_default_tail
    weight: 99
    keep_unmanaged: '{{ iptables_keep_unmanaged }}'
    state: '{{ (iptables_default_tail != "" ) | ternary("present", "absent") }}'
    rules: '{{ iptables_default_tail }}'
    ipversion: 4
  tags: iptables

- name: Set custom ip6tables rules
  iptables_raw:
    name: 'ip6tables_custom_rules_{{ item.name }}'
    weight: '{{ item.weight|default(omit) }}'
    keep_unmanaged: '{{ iptables_keep_unmanaged }}'
    rules: '{{ item.rules }}'
    state: '{{ item.state|default(omit) }}'
    table: '{{ item.table|default(omit) }}'
    ipversion: 6
  with_items: '{{ ip6tables_custom_rules }}'
  tags: iptables

- name: Set default ip6tables head rules
  iptables_raw:
    name: ip6tables_default_head
    weight: 10
    keep_unmanaged: '{{ iptables_keep_unmanaged }}'
    state: present
    rules: '{{ ip6tables_default_head }}'
    ipversion: 6
  tags: iptables

- name: Set default ip6tables tail rules
  iptables_raw:
    name: ip6tables_default_tail
    weight: 99
    keep_unmanaged: '{{ iptables_keep_unmanaged }}'
    state: '{{ (ip6tables_default_tail != "" ) | ternary("present", "absent") }}'
    rules: '{{ ip6tables_default_tail }}'
    ipversion: 6
  tags: iptables
