---
# tasks file for tvheadend
- name: install tvheadend
  package: name=tvheadend state=latest

- name: configure tvheadend superuser
  template:
    src: templates/var/lib/hts/.hts/tvheadend/superuser.j2
    dest: /var/lib/hts/.hts/tvheadend/superuser
    mode: 0600
    owner: hts
    group: hts
  notify:
    - restart tvheadend

- name: enable service
  service: name=tvheadend enabled=yes use=service
