---
#ansible_user: pi
#ansible_ssh_pass: raspberry

network_interfaces_manage_devices: true
network_interfaces_interfaces:
  - device: eth0
    family: inet
    method: dhcp
    triggers:
      - allow-hotplug
  - device: usb0
    family: inet
    method: dhcp
    triggers:
      - allow-hotplug

sshd_config_match:
  - condition: User pi
    keyword:
      PasswordAuthentication: "yes"
      ForceCommand: "internal-sftp"
      ChrootDirectory: "/home"

wireguard:
  wg0:
    privkey: "{{ vault_wg0_privkey }}"
    mtu: "{{ wireguard_wg0_mtu }}"
    auto_assign_ips: "{{ wireguard_wg0_auto_assign_ips }}"
    peers: "{{ wireguard_wg0_peers }}"
    gw: "{{ wireguard_wg0_gw }}"
