---
#ansible_user: pi
#ansible_ssh_pass: raspberry

network_interfaces_manage_devices: true
network_interfaces_interfaces:
  - device: eth0
    family: inet
    method: dhcp
    triggers:
      - allow-hotplug
  - device: usb0
    family: inet
    method: dhcp
    triggers:
      - allow-hotplug

sshd_config_match:
  - condition: User pi
    keyword:
      PasswordAuthentication: "yes"
      ForceCommand: "internal-sftp"
      ChrootDirectory: "/home"

wireguard_override:
  wg0:
    privkey: "{{ vault_wg0_privkey }}"
    pubkey: "{{ wireguard_default.wg0.peers.moviebox.pubkey }}"

wireguard: "{{ wireguard_client|combine(wireguard_override, recursive=True) }}"

ip6tables_custom_rules:
  - name: "tvheadend"
    rules: |
      -A INPUT -p tcp -m tcp --dport 9981 -m conntrack --ctstate NEW -j ACCEPT
      -A INPUT -p udp -m udp --dport 9981 -m conntrack --ctstate NEW -j ACCEPT
      -A INPUT -p tcp -m tcp --dport 9982 -m conntrack --ctstate NEW -j ACCEPT
      -A INPUT -p udp -m udp --dport 9982 -m conntrack --ctstate NEW -j ACCEPT
  - name: "socks"
    rules: |
      -A INPUT -p tcp -m tcp --dport 1080 -m conntrack --ctstate NEW -j ACCEPT

iptables_custom_rules: "{{ ip6tables_custom_rules }}"
