---
#ansible_user: pi
#ansible_ssh_pass: raspberry

network_interfaces_manage_devices: true
network_interfaces_interfaces:
  - device: eth0
    family: inet
    method: dhcp
    triggers:
      - allow-hotplug
  - device: usb0
    family: inet
    method: dhcp
    triggers:
      - allow-hotplug

sshd_config_match:
  - condition: User pi
    keyword:
      PasswordAuthentication: "yes"
      ForceCommand: "internal-sftp"
      ChrootDirectory: "/home"

_wireguard_custom:
  wg0:
    privkey: "{{ vault_wg0_privkey }}"

wireguard: "{{ wireguard_client|combine(_wireguard_custom, recursive=True) }}"

socks_proxy_port: 1080
socks_proxy_user: wgsocks

transmission_rpc_whitelist_enabled: False
transmission_rpc_auth_required: True
transmission_user: pi
transmission_password: "{{ vault_transmission_password }}"

transmission_download_dir: /home/pi/transmission/downloads
transmission_watch_dir: /home/pi/transmission/torrents
transmission_incomplete_dir_enabled: True
transmission_incomplete_dir: /home/pi/transmission/incomplete


nftables_includes:
  tvheadend:
    - |
      add rule inet filter input tcp dport 9981-9982 accept comment "accept tvheadend"
      add rule inet filter input udp dport 9981-9982 accept comment "accept tvheadend"
  socks_proxy:
    - |
      add rule inet filter input iifname "eth0" tcp dport {{ socks_proxy_port }} accept comment "socks connections"
      add rule inet filter output ct state {established, related} counter accept comment "accept all connections related to those we opened"
      add rule inet filter output meta skuid "{{ socks_proxy_user }}" oifname != "wg0" drop comment "{{ socks_proxy_user }} must go through wg0"
  transmission:
    - |
      add rule inet filter input tcp dport 9091 accept comment "transmission rpc"
      add rule inet filter input tcp dport 51413 accept comment "transmission torrent"
      add rule inet filter input udp dport 51413 accept comment "transmission torrent"
      add rule inet filter output ct state {established, related} counter accept comment "accept all connections related to those we opened"
      add rule inet filter output meta skuid "{{ transmission_user }}" oifname != "wg0" drop comment "{{ transmission_user }} must go through wg0"

iptables_common_rules:
  - name: tvheadend
    rules: |
      -A INPUT -p tcp -m tcp --dport 9981 -m conntrack --ctstate NEW -j ACCEPT
      -A INPUT -p udp -m udp --dport 9981 -m conntrack --ctstate NEW -j ACCEPT
      -A INPUT -p tcp -m tcp --dport 9982 -m conntrack --ctstate NEW -j ACCEPT
      -A INPUT -p udp -m udp --dport 9982 -m conntrack --ctstate NEW -j ACCEPT
  - name: socks
    rules: |
      -A INPUT -p tcp -m tcp --dport {{ socks_proxy_port }} -i eth0 -m conntrack --ctstate NEW -j ACCEPT
      -A OUTPUT -p tcp -m tcp --sport {{ socks_proxy_port }} -o eth0 -j ACCEPT
      -A OUTPUT -m owner --uid-owner {{ socks_proxy_user }} -o wg0 -j ACCEPT
      -A OUTPUT -m owner --uid-owner {{ socks_proxy_user }} -j REJECT
  - name: transmission
    rules: |
      -A INPUT -p tcp -m tcp --dport 9091 -i eth0 -m conntrack --ctstate NEW -j ACCEPT
      -A INPUT -p tcp -m tcp --dport 51413 -i wg0 -m conntrack --ctstate NEW -j ACCEPT
      -A INPUT -p udp -m udp --dport 51413 -i wg0 -m conntrack --ctstate NEW -j ACCEPT
      -A OUTPUT -p tcp -m tcp --sport 9091 -m owner --uid-owner {{ transmission_user }} -j ACCEPT
      -A OUTPUT -m owner --uid-owner {{ transmission_user }} -o wg0 -j ACCEPT
      -A OUTPUT -m owner --uid-owner {{ transmission_user }} -j REJECT

iptables_custom_rules_v4_specific:
  - name: transmission_rpc
    rules: |
      -A INPUT -p tcp -m tcp -s {{ wireguard.wg0.auto_assign_ranges|ipv4|first }} --dport 9091 -m conntrack --ctstate NEW -j ACCEPT

iptables_custom_rules_v6_specific:
  - name: transmission_rpc
    rules: |
      -A INPUT -p tcp -m tcp -s {{ wireguard.wg0.auto_assign_ranges|ipv6|first }} --dport 9091 -m conntrack --ctstate NEW -j ACCEPT

iptables_custom_rules: "{{ iptables_common_rules }} + {{ iptables_custom_rules_v4_specific }}"

ip6tables_custom_rules: "{{ iptables_common_rules }} + {{ iptables_custom_rules_v6_specific }}"

host_roles:
  - common
  - chmduquesne.network_interfaces
  - chmduquesne.wireguard
  - tvheadend
  - socks-proxy
  - chmduquesne.transmission
  - chmduquesne.nftables
