---
- name: get latest radvd
  package: name=radvd state=latest

- name: configure /etc/radvd.conf
  template:
    src: templates/etc/radvd.conf.j2
    dest: /etc/radvd.conf
    owner: root
    group: root
    mode: 0644
  notify: restart radvd

- name: enable service
  service: name=radvd enabled=yes use=service
  notify:
    - restart radvd
