---
# tasks file for letsencrypt

- name: Create /etc/certbot
  file:
    path: /etc/certbot
    state: directory
    mode: '0700'

- name: configure /etc/certbot/ovh.ini
  template:
    src: templates/etc/certbot/ovh.ini.j2
    dest: /etc/certbot/ovh.ini
    owner: root
    group: root
    mode: 0600

# Additional steps that are only required because python3-certbot-dns-ovh
# requires the unstable version of python3-certbot

###
- name: Gather the package facts
  package_facts:
    manager: auto

- name: Install python-certbot from unstable
  command: apt install -t unstable python3-certbot
  when: "'python3-certbot-dns-ovh' not in ansible_facts.packages"
###

- name: Get required certbot packages
  package: name=python3-certbot-dns-ovh state=latest

  #- name: check if we
  #  stat:
  #    path: /Users/mdtutorials2/Documents/Ansible/prompt.yaml
  #  register: file_details

# TODO: use expect
- name: Register to letsencrypt
  command: certbot register -m {{ vault_letsencrypt_email }} --agree-tos -n
  args:
    creates: /etc/letsencrypt/accounts

- name: Request certificates
  command: certbot certonly --dns-ovh --dns-ovh-credentials /etc/certbot/ovh.ini {{ vault_letsencrypt_domain_options }}
  args:
    creates: /etc/letsencrypt/live

- name: Install renewal-hooks
  copy:
    src: files/etc/letsencrypt/renewal-hooks/post/{{ item }}
    dest: /etc/letsencrypt/renewal-hooks/post/{{ item }}
    owner: root
    group: root
    mode: '0755'
  loop:
    - '01-combine-certificates'
    - '02-reload-haproxy'
