---
# tasks file for letsencrypt

- name: Create /etc/certbot
  file:
    path: /etc/certbot
    state: directory
    mode: '0700'

- name: configure /etc/certbot/ovh.ini
  template:
    src: templates/etc/certbot/ovh.ini.j2
    dest: /etc/certbot/ovh.ini
    owner: root
    group: root
    mode: 0600

# TODO: install it from unstable
#- name: get required certbot packages
#  package: name=python3-certbot state=latest

- name: get required certbot packages
  package: name=python3-certbot-dns-ovh state=latest


# TODO: use expect
- name: register certbot
  command: certbot register -m EMAIL
  args:
    creates: etc/letsencrypt/accounts

#- name: Create /etc/letsencrypt/renewal-hooks/post
#  file:
#    path: /etc/certbot
#    state: directory
#    mode: '0755'
#
#- name: add renewal-hook for restarting haproxy
#  copy:
#    src: files/etc/letsencrypt/renewal-hooks/post/02-haproxy
#    dest: /etc/letsencrypt/renewal-hooks/post/02-haproxy
#    owner: root
#    group: root
#    mode: '0755'
