---
# tasks file for letsencrypt

- name: Create /etc/certbot
  file:
    path: /etc/certbot
    state: directory
    mode: '0700'

- name: configure /etc/certbot/ovh.ini
  template:
    src: templates/etc/certbot/ovh.ini.j2
    dest: /etc/certbot/ovh.ini
    owner: root
    group: root
    mode: 0600

- name: get required certbot packages
  package: name={{ item }} state=latest
  with_items:
    - python3-certbot
    - python3-certbot-dns-ovh

- name: add renewal-hook for restarting haproxy
  copy:
    src: files/etc/letsencrypt/renewal-hooks/post/02-haproxy
    dest: /etc/letsencrypt/renewal-hooks/post/02-haproxy
    owner: root
    group: root
    mode: '0755'
