---
- hosts: clients
  tasks:
    - name: apply common settings
      include_role: name=common

    - name: configure wireguard
      include_role: name=chmduquesne.wireguard

    - name: configure tvheadend
      include_role: name=tvheadend

    - name: install a socks-proxy
      include_role: name=socks-proxy

    - name: install transmission
      include_role: name=ansible-transmission
