---

- set_fact:
    peers: []

- name: collect peers
  set_fact:
    peers: "{{ peers }} + [ item ]"
  with_inventory_hostnames:
    all
  when:
    - item != inventory_hostname
    - hostvars[item].wireguard is defined
    - wgnet in hostvars[item].wireguard

- set_fact:
    peers: "{{ peers | sort }}"

- set_fact:
    conf: "{{ wireguard[wgnet] }}"

- name: create config file
  template:
    src: templates/etc/wireguard/wgnet.conf.j2
    dest: "/etc/wireguard/{{ wgnet }}.conf"
    owner: root
    group: root
    mode: 0600

- name: configure interface
  include_tasks: configure_interface.yml

- name: configure firewall in gateway
  include_tasks: configure_firewall_in_gw.yml
  when: conf.in_gw is defined

- name: configure firewall out gateway
  include_tasks: configure_firewall_out_gw.yml
  when: conf.out_gw is defined
