---

- name: "collect the private key of {{ host }}"
  set_fact:
    privkey: "{{ wireguard[wgnet].peers[host].privkey | default('<your private key>') }}"

- name: "adjusting {{ host }} config variables"
  set_fact:
    conf: {}
    _conf: "{{ wireguard[wgnet]|combine({'privkey': privkey})|auto_assign_ips(host)|remove_peer(host) }}"

- name: "removing the fields that are irrelevant for mobile devices"
  set_fact:
    conf: "{{ conf|combine({item.key: item.value}) }}"
  with_dict: "{{ _conf }}"
  when: (item.key not in ('listenport', 'table', 'preup', 'postup', 'predown', 'postdown'))

- name: "adding the fields"
  set_fact:
    conf: "{{ conf|combine(wireguard_mobile_parameters[wgnet]|default(dict())) }}"

- name: "create {{ host }} config"
  template:
    src: templates/etc/wireguard/wgnet.conf.j2
    dest: "{{ wireguard_mobile_conf_dir }}/{{ wgnet }}.{{host}}.conf"
  delegate_to: 127.0.0.1
  become: false
