# iptables rules to apply for a private wifi router
---
- name: accept dns requests from clients
  iptables_raw:
    name: dns_wireguard
    rules: |
      -A INPUT -s {{ conf.in_gw.inet6_prefix }}::/{{ conf.in_gw.inet6_mask }} -p tcp -m tcp --dport 53 -m conntrack --ctstate NEW -j ACCEPT
      -A INPUT -s {{ conf.in_gw.inet6_prefix }}::/{{ conf.in_gw.inet6_mask }} -p udp -m udp --dport 53 -m conntrack --ctstate NEW -j ACCEPT
    ipversion: 6

- name: allow packets coming from inside the private wifi to be forwarded to the VPN server
  iptables_raw:
    name: wireguard_wifi_to_tunnel
    rules: "-A FORWARD -i {{ conf.in_gw.interface }} -o {{ wgnet }} -s {{ conf.in_gw.inet6_prefix }}::/{{ conf.in_gw.inet6_mask }} -m conntrack --ctstate NEW -j ACCEPT"
    ipversion: 6
