---
- name: set pre-up commands
  set_fact:
    net_pre_up:
      - ip link add dev {{ wgnet }} type wireguard
      - wg setconf {{ wgnet }} /etc/wireguard/{{ wgnet }}.conf
      - ip link set mtu 1420 dev {{ wgnet }}
      - wg-ip -6 dev {{ wgnet }} apply
      - wg-ip -4 dev {{ wgnet }} apply

- name: set up command
  set_fact:
    net_up:
      - ip link set dev {{ wgnet }} up

- name: manage routing
  include_tasks: "configure_routing_{{ mode }}.yml"

- name: set general settings
  set_fact:
    net_settings:
      device: "{{ wgnet }}"
      family: inet6
      method: manual
      pre-up: "{{ net_pre_up }}"
      up: "{{ net_up }}"
      post-up: "{{ net_post_up }}"
      down:
        - ip link del dev {{ wgnet }}

- name: add in network interfaces
  set_fact:
    network_interfaces_interfaces: "{{ network_interfaces_interfaces + [ net_settings ] }}"
  when: network_interfaces_interfaces is defined

- debug:
    var: network_interfaces_interfaces
  when: network_interfaces_interfaces is defined
