---
- name: enable ipv6 forwarding for all interfaces
  sysctl: name=net.ipv6.conf.all.forwarding value=1
  when: ('in_gw' in conf) or ('out_gw' in conf)

- name: enable ipv6 forwarding by default
  sysctl: name=net.ipv6.conf.default.forwarding value=1
  when: ('in_gw' in conf) or ('out_gw' in conf)

- name: enable ipv4 forwarding for all interfaces
  sysctl: name=net.ipv4.ip_forward value=1
  when: ('in_gw' in conf) or ('out_gw' in conf)

- name: routing dedicated subnet from out_gw to in_gw
  set_fact:
    post_up:
      - "ip route add {{ hostvars[item].wireguard[wgnet].in_gw.inet6_prefix }}::/{{ hostvars[item].wireguard[wgnet].in_gw.inet6_mask }} via {{ hostvars[item].wireguard[wgnet].pubkey | gen_ip(subnet='fd1a:6126:2887::/48') }} dev {{ wgnet }}"
  with_items:
    "{{ peers }}"
  when:
    - ('out_gw' in conf)
    - hostvars[item].wireguard[wgnet].in_gw is defined
    - hostvars[item].wireguard[wgnet].in_gw.inet6_prefix is defined

# Generate a table number from the interface name.
# see filter_plugins/gen_uint32.py
- set_fact:
    wgtable: "{{ wgnet | gen_uint32 }}"

- name: routing all wlan traffic to wireguard
  set_fact:
    post_up:
      - ip -6 route flush table {{ wgtable }}
      - ip -4 route flush table {{ wgtable }}
      - ip -6 route add default dev {{ wgnet }} table {{ wgtable }}
      - ip -4 route add default dev {{ wgnet }} table {{ wgtable }}
      - ip -6 rule add iif {{ conf.in_gw.interface }} lookup {{ wgtable }}
      - ip -4 rule add iif {{ conf.in_gw.interface }} lookup {{ wgtable }}
  when:
    - ('in_gw' in conf)

- name: set general settings
  set_fact:
    interface:
      device: "{{ wgnet }}"
      family: inet6
      method: manual
      pre-up:
        - ip link add dev {{ wgnet }} type wireguard
        - wg setconf {{ wgnet }} /etc/wireguard/{{ wgnet }}.conf
        - wg-ip -6 dev {{ wgnet }} apply
        - wg-ip -4 dev {{ wgnet }} apply
        - ip link set mtu {{ conf.mtu | default(1420) }} dev {{ wgnet }}
      up:
        - ip link set dev {{ wgnet }} up
      post-up: "{{ post_up }}"
      down:
        - ip link del dev {{ wgnet }}

- name: adding interface suggestion
  set_fact:
    wireguard_suggested_interfaces: "{{ wireguard_suggested_interfaces | default([]) }} + [ interface ]"
