---
- name: enable ipv6 forwarding for all interfaces
  sysctl: name=net.ipv6.conf.all.forwarding value=1
  when: (mode == 'in_gw') or (mode == 'out_gw')

- name: enable ipv6 forwarding by default
  sysctl: name=net.ipv6.conf.default.forwarding value=1
  when: (mode == 'in_gw') or (mode == 'out_gw')

- name: enable ipv4 forwarding for all interfaces
  sysctl: name=net.ipv4.ip_forward value=1
  when: (mode == 'in_gw') or (mode == 'out_gw')

- name: routing dedicated subnet from out_gw to in_gw
  set_fact:
    net_post_up:
      - 'ip route add {{ hostvars[item].wireguard[wgnet].in_gw.inet6_prefix }}::/{{ hostvars[item].wireguard[wgnet].in_gw.inet6_mask }} via {{ inet6_auto_addr[item] }} dev {{ wgnet }}'
  with_items:
    "{{ peers }}"
  when:
    - mode == 'out_gw'
    - hostvars[item].wireguard[wgnet].in_gw is defined
    - hostvars[item].wireguard[wgnet].in_gw.inet6_prefix is defined

# TODO: generate the table number from the hash of {{ wgnet }}
# -> printf "%d" 0x$(echo "wg0" | sha1sum | cut -b-4))
# 12749
- name: routing all wlan traffic to wireguard
  set_fact:
    net_post_up:
      - ip -6 route flush table 51820
      - ip -4 route flush table 51820
      - ip -6 route add default dev {{ wgnet }} table 51820
      - ip -4 route add default dev {{ wgnet }} table 51820
      - ip -6 rule add iif {{ conf.in_gw.interface }} lookup 51820
      - ip -4 rule add iif {{ conf.in_gw.interface }} lookup 51820
  when:
    - mode == 'in_gw'

- name: set general settings
  set_fact:
    net_settings:
      device: "{{ wgnet }}"
      family: inet6
      method: manual
      pre-up:
        - ip link add dev {{ wgnet }} type wireguard
        - wg setconf {{ wgnet }} /etc/wireguard/{{ wgnet }}.conf
        - wg-ip -6 dev {{ wgnet }} apply
        - wg-ip -4 dev {{ wgnet }} apply
        - ip link set mtu 1360 dev {{ wgnet }}
      up:
        - ip link set dev {{ wgnet }} up
      post-up: "{{ net_post_up }}"
      down:
        - ip link del dev {{ wgnet }}

- name: add in network interfaces
  set_fact:
    network_interfaces_interfaces: "{{ network_interfaces_interfaces + [ net_settings ] }}"
  when: network_interfaces_interfaces is defined

- debug:
    var: network_interfaces_interfaces
  when: network_interfaces_interfaces is defined
