---
- name: set creation command
  set_fact:
    net_pre_up: [ "ip link add dev $IFACE type wireguard" ]

- name: set add peer command
  set_fact:
    net_pre_up: "{{ net_pre_up }} + [ 'ip address add {{ conf.inet6_addr }} peer {{ hostvars[item].wireguard[net].inet6_addr }} dev {{ net }}' ]"
  with_items:
    "{{ peers }}"

- name: set setconf command
  set_fact:
    net_pre_up: "{{ net_pre_up }} + [ 'wg setconf $IFACE /etc/wireguard/${IFACE}.conf' ]"

- name: set up command
  set_fact:
    net_up:
      - ip link set up dev $IFACE

- name: manage routing
  include_tasks: "configure_routing_{{ mode }}.yml"

- name: set general settings
  set_fact:
    net_settings:
      device: "{{ net }}"
      family: inet6
      method: manual
      pre-up: "{{ net_pre_up }}"
      up: "{{ net_up }}"
      post-up: "{{ net_post_up }}"
      down:
        - ip link del dev $IFACE

- name: add in network interfaces
  set_fact:
    network_interfaces_interfaces: "{{ network_interfaces_interfaces + [ net_settings ] }}"
  when: network_interfaces_interfaces is defined

- debug:
    var: network_interfaces_interfaces
  when: network_interfaces_interfaces is defined
