---

- set_fact:
    conf: "{{ wireguard[wgnet] | add_pubkey(inventory_hostname) | remove_peer(inventory_hostname) | auto_assign_ips }}"

- set_fact:
    is_in_gw: "{{ conf | in_gw(inventory_hostname) }}"

- set_fact:
    is_out_gw: "{{ conf | out_gw(inventory_hostname) }}"

- set_fact:
    is_gw: "{{ is_in_gw or is_out_gw }}"

- name: create config file
  template:
    src: templates/etc/wireguard/wgnet.conf.j2
    dest: "/etc/wireguard/{{ wgnet }}.conf"
    owner: root
    group: root
    mode: 0600

- name: enable wg-quick
  systemd:
    name: "wg-quick@{{ wgnet }}"
    enabled: yes
    state: started

- name: configure firewall
  include_tasks: configure_firewall.yml
  when: conf.iptable_raw
