# iptables rules to apply for a private wifi router
---
- name: accept dns requests from clients
  iptables_raw:
    name: dns_wireguard
    rules: |
      -A INPUT -i {{ conf.in_gw.interface }} -p tcp -m tcp --dport 53 -m conntrack --ctstate NEW -j ACCEPT
      -A INPUT -i {{ conf.in_gw.interface }} -p udp -m udp --dport 53 -m conntrack --ctstate NEW -j ACCEPT
    ipversion: "{{ item }}"
  with_items:
    - 4
    - 6

- name: allow wifi traffic to be forwarded to wireguard
  iptables_raw:
    name: wireguard_wifi_to_tunnel
    rules: "-A FORWARD -i {{ conf.in_gw.interface }} -o {{ wgnet }} -m conntrack --ctstate NEW -j ACCEPT"
    ipversion: "{{ item }}"
  with_items:
    - 4
    - 6

- name: masquerade v4 packets coming from inside the private wifi
  iptables_raw:
    name: wireguard_wifi_to_tunnel
    table: nat
    rules: "-A POSTROUTING -o {{ wgnet }} -j MASQUERADE"
    ipversion: 4
