---

- name: expand the configuration
  set_fact:
    conf: "{{ wireguard[wgnet]|auto_assign_ips(inventory_hostname)|remove_peer(inventory_hostname) }}"

- name: create config file
  template:
    src: templates/etc/wireguard/wgnet.conf.j2
    dest: "/etc/wireguard/{{ wgnet }}.conf"
    owner: root
    group: root
    mode: 0600

- name: enable wg-quick
  systemd:
    name: "wg-quick@{{ wgnet }}"
    enabled: yes

- name: enable ip forwarding
  sysctl: name={{ item }} value=1
  with_items:
    - net.ipv6.conf.all.forwarding
    - net.ipv6.conf.default.forwarding
    - net.ipv4.ip_forward
  when: (('in_gw' in conf) or ('out_gw' in conf))

- name: configure firewall
  include_tasks: "configure_firewall_{{ wireguard_iptable_module }}.yml"

- name: configure unbound records
  include_tasks: configure_unbound_records.yml
  when: conf.unbound_records|default(false)

- name: create mobile config
  include_tasks: configure_mobile.yml
  with_items: "{{ conf.peers.keys()|list|sort }}"
  loop_control:
    loop_var: host
  when: wireguard_generate_mobile and wireguard[wgnet].peers[host].mobile|default(False)
