---
- set_fact:
    unbound_controllers: "{{ unbound.controllers | default([]) }}"

- name: add inet6 unbound controllers
  set_fact:
    unbound_controllers: "{{ unbound_controllers }} + [ '{{ inet6_auto_addr[item] }}/128' ]"
  with_items:
    "{{ peers }}"

- name: add inet unbound controllers
  set_fact:
    unbound_controllers: "{{ unbound_controllers }} + [ '{{ inet_auto_addr[item] }}/32' ]"
  with_items:
    "{{ peers }}"

- name: add unbound controllers
  set_fact:
    unbound_controllers: "{{ unbound_controllers }} + [ '{{ conf.in_gw.inet6_prefix }}::/{{ conf.in_gw.inet6_mask }}' ]"
  when:
    - conf.in_gw is defined
    - conf.in_gw.inet6_prefix is defined

- name: set unbound upstream
  set_fact:
    unbound_upstream: "{{ inet6_auto_addr[item] }}"
  with_items:
    "{{ peers }}"
  when:
    - hostvars[item].wireguard[wgnet].out_gw is defined

- name: prepare unbound config
  set_fact:
    unbound:
      controllers: "{{ unbound_controllers }}"
      recursive: "{{ unbound.recursive | default(false) }}"
      upstream: "{{ unbound_upstream | default(false) }}"
  when: unbound is defined

- debug:
    var: unbound
  when: unbound is defined
