---
- name: enable ip forwarding
  sysctl: name={{ item }} value=1
  with_items:
    - net.ipv6.conf.all.forwarding
    - net.ipv6.conf.default.forwarding
    - net.ipv4.ip_forward
  when: is_gw

- name: set addresses
  set_fact:
    addr: "{{ addr | default([]) }} + ['ip address add {{ item }} dev {{ wgnet }}']"
  with_items: "{{ conf.address }}"

- name: collect routing infos
  set_fact:
    subnet: "{{ conf.auto_assign_ips | ipv6 | first }}"
    routed_inet6: "{{ conf.gw.routed_inet6.prefix }}::/{{ conf.gw.routed_inet6.mask }}"
  when: ('gw' in conf) and ('routed_inet6' in conf.gw)

- name: routing dedicated subnet from out_gw to in_gw
  set_fact:
    route: "{{ route | default([]) }} + ['ip route add {{ routed_inet6 }} via {{ conf.peers[conf.gw.in.hostname].pubkey | gen_ip(subnet=subnet) }} dev {{ wgnet }}']"
  when: is_out_gw and 'in' in conf.gw and ('routed_inet6' in conf.gw)

- set_fact:
    wgtable: "{{ wgnet | gen_uint32 }}"

- name: routing all wlan traffic to wireguard
  set_fact:
    table:
      - ip -4 route flush table {{ wgtable }}
      - ip -4 route add default dev {{ wgnet }} table {{ wgtable }}
      - ip -4 rule add iif {{ conf.gw.in.interface }} lookup {{ wgtable }}
      - ip -6 route flush table {{ wgtable }}
      - ip -6 route add default dev {{ wgnet }} table {{ wgtable }}
      - ip -6 rule add iif {{ conf.gw.in.interface }} lookup {{ wgtable }}
  when: is_in_gw

- name: set general settings
  set_fact:
    interface:
      device: "{{ wgnet }}"
      family: inet6
      method: manual
      pre-up:
        - ip link add dev {{ wgnet }} type wireguard
        - wg setconf {{ wgnet }} /etc/wireguard/{{ wgnet }}.conf
        - ip link set mtu {{ conf.mtu | default(1420) }} dev {{ wgnet }}
      up:
        - ip link set dev {{ wgnet }} up
      post-up: "{{ addr | default([]) }} + {{ route | default([]) }} + {{ table | default([]) }}"
      down:
        - ip link del dev {{ wgnet }}

- name: adding interface suggestion
  set_fact:
    wireguard_suggested_interfaces: "{{ wireguard_suggested_interfaces | default([]) }} + [ interface ]"
