# iptables rules to apply for an out gateway
---

- name: accept wireguard connections
  iptables_raw:
    name: "{{ wgnet }}_protocol"
    rules: "-A INPUT -p udp -m udp --dport {{ conf.listenport }} -m conntrack --ctstate NEW -j ACCEPT"
    ipversion: "{{ item }}"
  with_items:
    - 4
    - 6

- name: allow forwarding of packets that stay in the tunnel
  iptables_raw:
    name: "{{ wgnet }}_to_{{ wgnet }}"
    rules: "-A FORWARD -i {{ wgnet }} -o {{ wgnet }} -m conntrack --ctstate NEW -j ACCEPT"
    ipversion: "{{ item }}"
  with_items:
    - 4
    - 6

- name: allow forwarding of packets from peers to the Internet
  iptables_raw:
    name: "{{ wgnet }}_to_{{ conf.gw.out.interface }}"
    rules: "-A FORWARD -i {{ wgnet }} -o {{ conf.gw.out.interface }} -m conntrack --ctstate NEW -j ACCEPT"
    ipversion: "{{ item }}"
  with_items:
    - 4
    - 6

- name: masquerade v4 packets
  iptables_raw:
    name: "{{ wgnet }}_masquerade"
    table: nat
    rules: "-A POSTROUTING -o {{ conf.gw.out.interface }} -j MASQUERADE"
    ipversion: 4
