# iptables rules to apply for a private wifi router
---
- set_fact:
    rules_v4: []
    rules_v6: []

- name: accept dns requests from clients
  set_fact:
    rule:
      name: dns_wireguard
      rules: |
        -A INPUT -i {{ conf.in_gw.interface }} -p tcp -m tcp --dport 53 -m conntrack --ctstate NEW -j ACCEPT
        -A INPUT -i {{ conf.in_gw.interface }} -p udp -m udp --dport 53 -m conntrack --ctstate NEW -j ACCEPT

- set_fact:
    rules_v4: "{{ rules_v4 + [ rule ] }}"
    rules_v6: "{{ rules_v6 + [ rule ] }}"

- name: allow wifi traffic to be forwarded to wireguard
  set_fact:
    rule:
      name: wireguard_wifi_to_tunnel
      rules: "-A FORWARD -i {{ conf.in_gw.interface }} -o {{ wgnet }} -m conntrack --ctstate NEW -j ACCEPT"

- set_fact:
    rules_v4: "{{ rules_v4 + [ rule ] }}"
    rules_v6: "{{ rules_v6 + [ rule ] }}"

- name: masquerade v4 packets coming from inside the private wifi
  set_fact:
    rule:
      name: wireguard_wifi_to_tunnel
      table: nat
      rules: "-A POSTROUTING -o {{ wgnet }} -j MASQUERADE"

- set_fact:
    rules_v4: "{{ rules_v4 + [ rule ] }}"

- set_fact:
    wireguard_suggested_iptables: "{{ wireguard_suggested_iptables | default([]) }} + rules_v4"

- set_fact:
    wireguard_suggested_ip6tables: "{{ wireguard_suggested_ip6tables | default([]) }} + rules_v6"
