---
- set_fact:
    unbound_controllers: "{{ unbound.controllers | default([]) }}"

- name: add unbound controllers
  set_fact:
    unbound_controllers: "{{ unbound_controllers }} + [ '{{ hostvars[item].wireguard[net].inet6_addr }}/128' ]"
  with_items:
    "{{ other_wireguard_hosts }}"
  when:
    - wireguard[net].public is defined
    - wireguard[net].public

- name: add unbound controllers
  set_fact:
    unbound_controllers: "{{ unbound_controllers }} + [ '{{ wireguard[net].router.inet6_prefix }}::/{{ wireguard[net].router.inet6_mask }}' ]"
  when:
    - wireguard[net].router is defined
    - wireguard[net].router.inet6_prefix is defined

- name: set unbound upstream
  set_fact:
    unbound_upstream: "{{ hostvars[item].wireguard[net].inet6_addr }}/128"
  with_items:
    "{{ other_wireguard_hosts }}"
  when:
    - wireguard[net].public is not defined
    - hostvars[item].wireguard[net].public is defined
    - hostvars[item].wireguard[net].public

- name: prepare unbound config
  set_fact:
    unbound:
      controllers: "{{ unbound_controllers }}"
      recursive: "{{ unbound.recursive | default(false) }}"
      upstream: "{{ unbound_upstream | default(false) }}"
  when: unbound is defined

- debug:
    var: unbound
  when: unbound is defined
