# iptables rules to apply for a private wifi router
---
- name: accept dns requests from clients
  iptables_raw:
    name: dns_wireguard
    rules: |
      -A INPUT -s {{ conf.in_gw.inet6_prefix }}::/{{ conf.in_gw.inet6_mask }} -p tcp -m tcp --dport 53 -m conntrack --ctstate NEW -j ACCEPT
      -A INPUT -s {{ conf.in_gw.inet6_prefix }}::/{{ conf.in_gw.inet6_mask }} -p udp -m udp --dport 53 -m conntrack --ctstate NEW -j ACCEPT
    ipversion: 6

- name: allow v6 packets coming from inside the private wifi to be forwarded to the VPN server
  iptables_raw:
    name: wireguard_wifi_to_tunnel_v6
    rules: "-A FORWARD -i {{ conf.in_gw.interface }} -o {{ wgnet }} -s {{ conf.in_gw.inet6_prefix }}::/{{ conf.in_gw.inet6_mask }} -m conntrack --ctstate NEW -j ACCEPT"
    ipversion: 6

- name: allow forwarding of packets from peers to the Internet
  iptables_raw:
    name: wireguard_wifi_to_tunnel_v4
    rules: "-A FORWARD -i {{ conf.in_gw.interface }} -o {{ wgnet }} -m conntrack --ctstate NEW -j ACCEPT"
    ipversion: 4

- name: masquerade v4 packets coming from inside the private wifi
  iptables_raw:
    name: wireguard_wifi_to_tunnel
    table: nat
    rules: "-A POSTROUTING -o {{ wgnet }} -j MASQUERADE"
    ipversion: 4
