---

- set_fact:
    conf: "{{ wireguard[wgnet] | add_pubkey(inventory_hostname) | remove_peer(inventory_hostname) | auto_assign_ips }}"

- set_fact:
    is_in_gw: "{{ ('gw' in conf) and ('in' in conf.gw) and (conf.gw.in.hostname == inventory_hostname) }}"

- set_fact:
    is_out_gw: "{{ ('gw' in conf) and ('out' in conf.gw) and (conf.gw.out.hostname == inventory_hostname) }}"

- set_fact:
    is_gw: "{{ is_in_gw or is_out_gw }}"

- debug:
    var: conf

- name: create config file
  template:
    src: templates/etc/wireguard/wgnet.conf.j2
    dest: "/etc/wireguard/{{ wgnet }}.conf"
    owner: root
    group: root
    mode: 0600

- name: configure interface
  include_tasks: configure_interface.yml

- name: configure firewall in gateway
  include_tasks: configure_firewall_in_gw.yml
  when: is_in_gw

- name: configure firewall out gateway
  include_tasks: configure_firewall_out_gw.yml
  when: is_out_gw
