# iptables rules for a private wifi router
---
- name: allow wifi traffic to be forwarded to wireguard
  iptables_raw:
    name: "{{ wgnet }}_wifi_to_vpn"
    rules: "-A FORWARD -i {{ conf.gw.in.interface }} -o {{ wgnet }} -m conntrack --ctstate NEW -j ACCEPT"
    ipversion: "{{ item }}"
  with_items:
    - 4
    - 6

- name: masquerade v4 packets coming from inside the private wifi
  iptables_raw:
    name: "{{ wgnet }}_masquerade_wifi"
    table: nat
    rules: "-A POSTROUTING -o {{ wgnet }} -j MASQUERADE"
    ipversion: 4
