# iptables rules to apply for an out gateway
---

- name: accept wireguard connections
  iptables_raw:
    name: "wireguard_accept_connections"
    rules: "-A INPUT -p udp -m udp --dport {{ conf.listenport }} -m conntrack --ctstate NEW -j ACCEPT"
    ipversion: "{{ item }}"
  with_items:
    - 4
    - 6

- name: accept dns requests from peers
  iptables_raw:
    name: "dns_wireguard_{{ item }}"
    rules: |
      -A INPUT -s {{ inet6_auto_addr[item] }}/128 -p tcp -m tcp --dport 53 -m conntrack --ctstate NEW -j ACCEPT
      -A INPUT -s {{ inet6_auto_addr[item] }}/128 -p udp -m udp --dport 53 -m conntrack --ctstate NEW -j ACCEPT
    ipversion: 6
  with_items:
    - "{{ peers }}"

- name: allow forwarding of packets that stay in the tunnel
  iptables_raw:
    name: wireguard_peer_to_peer_forwarding
    rules: "-A FORWARD -i {{ wgnet }} -o {{ wgnet }} -m conntrack --ctstate NEW -j ACCEPT"
    ipversion: "{{ item }}"
  with_items:
    - 4
    - 6

- name: allow forwarding of packets from peers to the Internet
  iptables_raw:
    name: "wireguard_{{ item }}_to_internet"
    rules: "-A FORWARD -i {{ wgnet }} -o {{ conf.out_gw.interface }} -m conntrack --ctstate NEW -j ACCEPT"
    ipversion: 6
  with_items:
    - "{{ peers }}"
  when:
    - hostvars[item].wireguard[wgnet].in_gw is defined
    - hostvars[item].wireguard[wgnet].in_gw.inet6_prefix is defined

- name: allow forwarding of packets from peers to the Internet
  iptables_raw:
    name: "wireguard_{{ item }}_to_internet"
    rules: "-A FORWARD -i {{ wgnet }} -o {{ conf.out_gw.interface }} -m conntrack --ctstate NEW -j ACCEPT"
    ipversion: 4
  with_items:
    - "{{ peers }}"
  when:
    - hostvars[item].wireguard[wgnet].in_gw is defined
