---

- name: expand the configuration
  set_fact:
    conf: "{{ wireguard[wgnet]|add_pubkey(inventory_hostname)|remove_peer(inventory_hostname)|auto_assign_ips }}"

- name: create config file
  template:
    src: templates/etc/wireguard/wgnet.conf.j2
    dest: "/etc/wireguard/{{ wgnet }}.conf"
    owner: root
    group: root
    mode: 0600

- name: enable wg-quick
  systemd:
    name: "wg-quick@{{ wgnet }}"
    enabled: yes
    state: started
  when: not wireguard_mobile

- name: enable ip forwarding
  sysctl: name={{ item }} value=1
  with_items:
    - net.ipv6.conf.all.forwarding
    - net.ipv6.conf.default.forwarding
    - net.ipv4.ip_forward
  when: (conf|in_gw(inventory_hostname) or conf|out_gw(inventory_hostname)) and not wireguard_mobile

- name: configure firewall in gateway
  include_tasks: configure_firewall_in_gw.yml
  when: conf|in_gw(inventory_hostname) and not wireguard_mobile

- name: configure firewall out gateway
  include_tasks: configure_firewall_out_gw.yml
  when: conf|out_gw(inventory_hostname) and not wireguard_mobile
