---
- name: get latest git
  package: name=git state=latest

- name: clone wg-ip
  git:
    repo: https://github.com/chmduquesne/wg-ip.git
    dest: wg-ip
  register: wgip_repo
  become: false

- name: put wg-ip in the path
  shell: install -m 755 wg-ip /usr/bin/wg-ip
  args:
    chdir: wg-ip
  when: wgip_repo.before != wgip_repo.after

