---
- name: install wireguard from distrib
  import_tasks: install_wireguard_debian_x86_64.yml
  when: ansible_os_family == "Debian" and ansible_machine == "x86_64"

- name: install wireguard from source
  import_tasks: install_wireguard_from_source_armv7l.yml
  when: ansible_os_family == "Debian" and ansible_machine == "armv7l"
