---
- name: install wireguard
  include_tasks: "install_{{ ansible_os_family }}_{{ ansible_machine }}.yml"

- name: install wg-ip
  include_tasks: install_wg-ip.yml

- name: configure networks
  include_tasks: configure_wgnet.yml
  with_items:
    "{{ wireguard.keys() }}"
  loop_control:
    loop_var: wgnet
