---
- name: install wireguard from distrib
  import_tasks: install_wireguard_debian_x86_64.yml
  when: ansible_os_family == "Debian" and ansible_machine == "x86_64"

- name: install wireguard from source
  import_tasks: install_wireguard_from_source_armv7l.yml
  when: ansible_os_family == "Debian" and ansible_machine == "armv7l"

- name: configure /etc/wireguard/wg0.conf
  template:
    src: templates/etc/wireguard/wg0.conf.j2
    dest: /etc/wireguard/wg0.conf
    owner: root
    group: root
    mode: 0600

- name: wg0 pre-up commands create device
  set_fact:
    wg0_pre_up: [ "ip link add dev $IFACE type wireguard" ]

- name: wg0 pre-up commands add peers
  set_fact:
    wg0_pre_up: "{{ wg0_pre_up }} + [ 'ip address add {{ wireguard.private_ip6 }} peer {{ hostvars[item].wireguard.private_ip6 }} dev wg0' ]"
  with_inventory_hostnames:
    all
  when: item != inventory_hostname and "wireguard" in hostvars[item]

- name: wg0 pre-up commands setconf
  set_fact:
    wg0_pre_up: "{{ wg0_pre_up }} + [ 'wg setconf wg0 /etc/wireguard/wg0.conf' ]"

- name: wg0 up commands set device up
  set_fact:
    wg0_up:
      - ip link set up dev $IFACE
      - echo 1 > /proc/sys/net/ipv6/conf/$IFACE/forwarding

- name: wg0 up commands add route
  set_fact:
    wg0_up: "{{ wg0_up }} + [ 'ip route add {{ hostvars[item].wireguard.routed_ip6 }} via {{ hostvars[item].wireguard.private_ip6 }} dev wg0' ]"
  with_inventory_hostnames:
    all
  when:
    - item != inventory_hostname
    - hostvars[item].wireguard is defined
    - hostvars[item].wireguard.routed_ip6 is defined

- name: set wg0 fact
  set_fact:
    wg0_settings:
      device: wg0
      family: inet6
      method: manual
      pre-up: "{{ wg0_pre_up }}"
      up: "{{ wg0_up }}"
      down:
        - ip link del dev wg0

- name: add wg0 in network interfaces
  set_fact:
    network_interfaces_interfaces: "{{ network_interfaces_interfaces + [wg0_settings] }}"
  when: network_interfaces_interfaces is defined

- debug:
    var: network_interfaces_interfaces
  when: network_interfaces_interfaces is defined

- name: enable ipv6 forwarding for all interfaces
  sysctl: name=net.ipv6.conf.all.forwarding value=1
  when: wireguard.router
